import { dirname, isAbsolute, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Local-file default. The same env var accepts a remote libSQL URL
 * (`libsql://…`, e.g. Turso) with no other changes.
 */
export const DEFAULT_DATABASE_URL = 'file:./data/quintal.db';

/** `packages/shared` — identical depth whether running from `src/` or `dist/`. */
export const PACKAGE_ROOT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../..',
);

/** Repo root. Relative `file:` DB paths resolve from here, not from cwd. */
export const WORKSPACE_ROOT = resolve(PACKAGE_ROOT, '../..');

/** Migrations generated by drizzle-kit, applied automatically on server boot. */
export const MIGRATIONS_FOLDER = resolve(PACKAGE_ROOT, 'drizzle');

export interface ResolvedDatabaseUrl {
  /** URL to hand to `@libsql/client`. */
  url: string;
  /** Absolute filesystem path, for `file:` URLs only. */
  filePath: string | null;
  isRemote: boolean;
}

/**
 * Resolve `DATABASE_URL` into something libSQL can open.
 *
 * Relative `file:` paths are resolved against the repo root so that
 * `pnpm dev` and `pnpm start` hit the same database no matter which package
 * the process was launched from.
 */
export function resolveDatabaseUrl(
  raw: string = process.env.DATABASE_URL ?? DEFAULT_DATABASE_URL,
  baseDir: string = process.env.QUINTAL_DATA_ROOT ?? WORKSPACE_ROOT,
): ResolvedDatabaseUrl {
  if (!raw.startsWith('file:')) {
    return { url: raw, filePath: null, isRemote: true };
  }

  const path = raw.slice('file:'.length);
  const absolute = isAbsolute(path) ? path : resolve(baseDir, path);
  return { url: `file:${absolute}`, filePath: absolute, isRemote: false };
}
