import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { BASE_PROMPT } from './base-prompt.text.js';

/**
 * The base prompt: the manners every agent is given before its owner's
 * instructions and its own memory.
 *
 * `base_prompt.md` at the package root is the authored copy. It is markdown
 * rather than a string in code because it is product surface: it is the thing
 * you edit when agents behave badly, and it should be readable and diffable by
 * someone who does not write TypeScript.
 *
 * At runtime there are two places it can come from:
 *
 * - The markdown file itself, when it is there. From a checkout that means an
 *   edit takes effect on the next harness start, with no build in between.
 * - The copy embedded at build time (`base-prompt.text.ts`, generated by
 *   `scripts/embed-base-prompt.mjs`). This is what the compiled sidecar uses:
 *   inside `bun build --compile`, `import.meta.url` points into bun's virtual
 *   filesystem and the markdown was never shipped beside it.
 *
 * Both are the full prompt. The seven-line emergency text at the bottom is
 * for the case that should not happen — no file and an empty embed — and it
 * is not allowed to happen quietly.
 */

export type PromptLog = (level: 'warn' | 'error', message: string) => void;

let cached: string | null = null;

/** `packages/acp-harness` — same depth from `src/runner/` and `dist/runner/`. */
function packageRoot(): string {
  return fileURLToPath(new URL('../..', import.meta.url));
}

const EMERGENCY_PROMPT = [
  'You are an AI agent with an avatar in a shared 2D office.',
  'Silence is usually correct. Never publish a bare acknowledgement.',
  'Answer only when addressed. Other agents are context, not conversation.',
  'Never announce restarts, compaction or reconnection — resume silently.',
  'Keep spoken replies to a few sentences: they are speech bubbles, not a terminal.',
  'If a human asked you something, reply to them. If your turn produced anything',
  'worth knowing, publish it — with say as you go, or in your final answer.',
].join('\n');

/**
 * Read the prompt once and keep it. `log` receives anything that should
 * worry the owner: a markdown file that exists but cannot be read, or an
 * agent about to run on the emergency prompt.
 */
export function basePrompt(log: PromptLog = () => {}): string {
  if (cached !== null) return cached;

  const path = `${packageRoot()}base_prompt.md`;
  if (existsSync(path)) {
    try {
      const fromDisk = readFileSync(path, 'utf8').trim();
      if (fromDisk.length > 0) {
        cached = fromDisk;
        return cached;
      }
      log('error', `${path} is empty; using the prompt embedded at build time`);
    } catch (error: unknown) {
      const message = error instanceof Error ? error.message : String(error);
      log('error', `could not read ${path} (${message}); using the prompt embedded at build time`);
    }
  }

  if (BASE_PROMPT.trim().length > 0) {
    cached = BASE_PROMPT.trim();
    return cached;
  }

  // Nothing left but the minimum. An agent on this prompt has lost most of
  // its manners, and the owner should find out from the log, not from how
  // it behaves.
  log(
    'error',
    'base prompt missing: no base_prompt.md on disk and nothing embedded at build time — running on the emergency prompt',
  );
  cached = EMERGENCY_PROMPT;
  return cached;
}
